name: diatonic
description: A Dart library for music.
version: 0.1.0
# homepage: https://www.example.com
author: mockturtl <mockturtl@gmail.com>

environment:
  sdk: '>=2.1.1 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.5.0
  pedantic: ^1.5.0
